# Generated by Django 5.2.4 on 2025-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0002_remove_photo_experienc_photo_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
