# Generated by Django 5.2.4 on 2025-07-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0002_alter_wishlist_experience_alter_wishlist_rooms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="experience",
            new_name="experiences",
        ),
    ]
